# Generated by Django 3.0.6 on 2020-05-17 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='first_name',
            field=models.CharField(default='Pas de prénoms', max_length=200),
        ),
        migrations.AddField(
            model_name='membre',
            name='inscription_date_robopoly',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='membre',
            name='mail',
            field=models.CharField(default='Pas de mail', max_length=200),
        ),
        migrations.AddField(
            model_name='membre',
            name='section',
            field=models.CharField(default='Pas de section', max_length=20),
        ),
        migrations.AddField(
            model_name='membre',
            name='title',
            field=models.CharField(default='Pas de titre', max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='name',
            field=models.CharField(default='Pas de noms', max_length=200),
        ),
    ]
