# Generated by Django 3.0.6 on 2020-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_auto_20200517_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='section',
            field=models.CharField(default='Pas de section', max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='title',
            field=models.CharField(default='Pas de titre', max_length=10),
        ),
    ]
