# Generated by Django 3.0.6 on 2020-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_auto_20200519_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='phone_num',
            field=models.CharField(default='Pas de numéro', max_length=20),
        ),
    ]
