# Generated by Django 3.0.6 on 2020-09-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_membre_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
